# Generated by Django 3.1.3 on 2020-11-04 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter Item Name (e.g. Laminate Sheet)', max_length=100, verbose_name='Item Name')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity must alteast be zero!')], verbose_name='Item Quantity')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='Item Minimum Quantity')),
                ('quantity_type', models.CharField(choices=[('nos', 'Numbers'), ('ltr', 'Litres'), ('mtr', 'Meters'), ('cm', 'Centimeters'), ('mm', 'Millimeters'), ('kgs', 'Kilograms'), ('pcs', 'Pieces'), ('ft', 'Feet'), ('sqft', 'SquareFeet')], default='nos', max_length=20, verbose_name='Item Quantity Type')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
